version: '3.1'

services:

  server:
    image: nginx:alpine
    container_name: query-monitor-server
    restart: always
    ports:
      - 80
    depends_on:
      - php
    volumes:
      - ./vendor/johnbillion/plugin-infrastructure/tests/nginx.conf:/etc/nginx/templates/default.conf.template
      - ./vendor/roots/wordpress:/var/www/html/:rw
      - ./vendor/johnbillion/plugin-infrastructure/tests/wp-config.php:/var/www/html/wp-config.php
      - ./:/var/www/html/wp-content/plugins/query-monitor:rw
    networks:
      - query-monitor

  php:
    image: wordpressdevelop/php:${LOCAL_PHP-8.0}-fpm
    container_name: query-monitor-php
    restart: always
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DEBUG: ${LOCAL_WP_DEBUG-1}
    depends_on:
      - database
    init: true
    volumes:
      - ./vendor/roots/wordpress:/var/www/html/:rw
      - ./vendor/johnbillion/plugin-infrastructure/tests/wp-config.php:/var/www/html/wp-config.php
      - ./vendor/johnbillion/plugin-infrastructure/tests/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./:/var/www/html/wp-content/plugins/query-monitor:rw
    networks:
      - query-monitor

  database:
    image: mariadb:10.5.8
    container_name: query-monitor-database
    restart: always
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - database:/var/lib/mysql:rw
    networks:
      - query-monitor

  wpcli:
    image: wordpressdevelop/cli:${LOCAL_PHP-8.0}-fpm
    container_name: query-monitor-wpcli
    environment:
      WORDPRESS_DB_HOST: database
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    depends_on:
      - database
      - php
    init: true
    volumes:
      - ./vendor/roots/wordpress:/var/www/:rw
      - ./vendor/johnbillion/plugin-infrastructure/tests/wp-config.php:/var/www/wp-config.php
      - ./vendor/johnbillion/plugin-infrastructure/tests/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini
      - ./:/var/www/wp-content/plugins/query-monitor:rw
    networks:
      - query-monitor

  chrome:
    image: seleniarm/standalone-chromium
    container_name: query-monitor-chrome
    profiles:
      - acceptance-tests
    depends_on:
      - server
    ports:
      - 4444
    extra_hosts:
      - host.docker.internal:host-gateway
    shm_size: 2gb
    networks:
      - query-monitor

volumes:
  database:

networks:
  query-monitor:
    driver: bridge
