# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Build
on:
  push:
    branches:
      - 'release'
      - 'test-release'

jobs:
  build:
    name: Build
    uses: johnbillion/plugin-infrastructure/.github/workflows/reusable-build.yml@trunk
    with:
      test: ${{ github.ref_name == 'test-release' }}
