# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: Coding Standards
on:
  push:
    branches:
      - 'develop'
      - 'trunk'
      - 'master'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  test:
    uses: johnbillion/plugin-infrastructure/.github/workflows/coding-standards.yml@trunk
